services:
  postgres:
    container_name: postgres
    image: ${POSTGRES_IMAGE:-postgres:16}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      DB_STORAGE_TYPE: "SSD"
    volumes:
      - ${POSTGRES_VOLUME_DATA}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    shm_size: 128mb
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    external: true
