services:
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION:-8-alpine}
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # When using password, uncomment the following line
    # environment:
    #   - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    # command: >
    #   sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""
    # healthcheck:
    #   test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256m
    networks:
      - shared

volumes:
  redis_data:

networks:
  shared:
    external: true
